// Universal Model Registry — 70+ free models with structured metadata.
// Real models (isReal: true) are backed by z-ai-web-dev-sdk (GLM family).
// All others are fully registered with realistic metadata and simulated
// health/benchmarks so routing decisions read from real metadata, never hardcoded.

export type ModelCapability = {
  id: string;
  provider: string;
  family: string;
  displayName: string;
  contextLength: number;
  maxOutputTokens: number;
  speedScore: number;       // 0-100
  qualityScore: number;
  reasoningScore: number;
  codingScore: number;
  mathScore: number;
  writingScore: number;
  multilingualScore: number;
  visionSupport: boolean;
  toolCalling: boolean;
  functionCalling: boolean;
  jsonMode: boolean;
  structuredOutput: boolean;
  embeddingSupport: boolean;
  streaming: boolean;
  freeOrPaid: "free" | "paid";
  benchmarkScore: number;   // aggregate
  healthScore: number;      // 0-100
  isReal: boolean;          // backed by z-ai-web-dev-sdk
  description: string;
};

export const MODEL_REGISTRY: ModelCapability[] = [
  // ===================== ZAI / GLM (REAL) =====================
  {
    id: "glm-4.7", provider: "zai", family: "glm", displayName: "GLM-4.7",
    contextLength: 128000, maxOutputTokens: 8192,
    speedScore: 78, qualityScore: 94, reasoningScore: 92, codingScore: 93,
    mathScore: 90, writingScore: 95, multilingualScore: 94,
    visionSupport: true, toolCalling: true, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 92.3, healthScore: 99, isReal: true,
    description: "Flagship GLM model with strong reasoning, coding, and vision. Routed live via z-ai-web-dev-sdk.",
  },
  {
    id: "glm-4.7-flash", provider: "zai", family: "glm", displayName: "GLM-4.7 Flash",
    contextLength: 128000, maxOutputTokens: 8192,
    speedScore: 96, qualityScore: 88, reasoningScore: 85, codingScore: 87,
    mathScore: 84, writingScore: 90, multilingualScore: 90,
    visionSupport: true, toolCalling: true, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 87.1, healthScore: 99, isReal: true,
    description: "Low-latency GLM variant optimized for speed while retaining broad capability. Routed live.",
  },

  // ===================== DeepSeek =====================
  {
    id: "deepseek-v3.1", provider: "openrouter", family: "deepseek", displayName: "DeepSeek V3.1",
    contextLength: 64000, maxOutputTokens: 8192,
    speedScore: 70, qualityScore: 93, reasoningScore: 91, codingScore: 95,
    mathScore: 96, writingScore: 88, multilingualScore: 86,
    visionSupport: false, toolCalling: true, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 91.4, healthScore: 96, isReal: false,
    description: "MoE model with elite coding and math performance.",
  },
  {
    id: "deepseek-v3.1-reasoning", provider: "openrouter", family: "deepseek", displayName: "DeepSeek V3.1 Reasoning",
    contextLength: 64000, maxOutputTokens: 16384,
    speedScore: 52, qualityScore: 95, reasoningScore: 97, codingScore: 93,
    mathScore: 98, writingScore: 84, multilingualScore: 84,
    visionSupport: false, toolCalling: true, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 93.8, healthScore: 93, isReal: false,
    description: "Deep reasoning variant; top-tier for complex multi-step problems.",
  },
  {
    id: "deepseek-math-v2", provider: "openrouter", family: "deepseek", displayName: "DeepSeekMath V2",
    contextLength: 32000, maxOutputTokens: 4096,
    speedScore: 68, qualityScore: 90, reasoningScore: 93, codingScore: 80,
    mathScore: 99, writingScore: 72, multilingualScore: 78,
    visionSupport: false, toolCalling: false, functionCalling: false, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 89.6, healthScore: 95, isReal: false,
    description: "Specialized mathematics model with near-perfect competition math scores.",
  },
  {
    id: "deepseek-r1-distill", provider: "openrouter", family: "deepseek", displayName: "DeepSeek R1 Distill",
    contextLength: 64000, maxOutputTokens: 16384,
    speedScore: 74, qualityScore: 88, reasoningScore: 92, codingScore: 86,
    mathScore: 94, writingScore: 80, multilingualScore: 80,
    visionSupport: false, toolCalling: true, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 87.9, healthScore: 94, isReal: false,
    description: "Distilled reasoning model balancing speed and depth.",
  },

  // ===================== Qwen =====================
  {
    id: "qwen2.5-coder", provider: "openrouter", family: "qwen", displayName: "Qwen2.5 Coder",
    contextLength: 128000, maxOutputTokens: 8192,
    speedScore: 76, qualityScore: 90, reasoningScore: 84, codingScore: 96,
    mathScore: 82, writingScore: 78, multilingualScore: 88,
    visionSupport: false, toolCalling: true, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 88.7, healthScore: 96, isReal: false,
    description: "Code-specialized Qwen with long context for large repos.",
  },
  {
    id: "qwen2.5-72b", provider: "openrouter", family: "qwen", displayName: "Qwen2.5 72B",
    contextLength: 128000, maxOutputTokens: 8192,
    speedScore: 60, qualityScore: 92, reasoningScore: 90, codingScore: 88,
    mathScore: 89, writingScore: 90, multilingualScore: 95,
    visionSupport: false, toolCalling: true, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 90.1, healthScore: 94, isReal: false,
    description: "Large general-purpose Qwen; exceptional multilingual coverage.",
  },
  {
    id: "qwen2.5-vl", provider: "openrouter", family: "qwen", displayName: "Qwen2.5 VL",
    contextLength: 128000, maxOutputTokens: 8192,
    speedScore: 66, qualityScore: 89, reasoningScore: 84, codingScore: 76,
    mathScore: 80, writingScore: 84, multilingualScore: 90,
    visionSupport: true, toolCalling: true, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 86.2, healthScore: 95, isReal: false,
    description: "Vision-language Qwen for OCR, charts, and document understanding.",
  },
  {
    id: "qwen2.5-1m", provider: "openrouter", family: "qwen", displayName: "Qwen2.5 1M",
    contextLength: 1000000, maxOutputTokens: 8192,
    speedScore: 58, qualityScore: 88, reasoningScore: 86, codingScore: 82,
    mathScore: 84, writingScore: 86, multilingualScore: 92,
    visionSupport: false, toolCalling: true, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 85.4, healthScore: 92, isReal: false,
    description: "Ultra-long 1M context window for massive documents.",
  },
  {
    id: "qwen3", provider: "openrouter", family: "qwen", displayName: "Qwen3",
    contextLength: 128000, maxOutputTokens: 8192,
    speedScore: 72, qualityScore: 91, reasoningScore: 90, codingScore: 89,
    mathScore: 90, writingScore: 89, multilingualScore: 93,
    visionSupport: false, toolCalling: true, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 89.3, healthScore: 95, isReal: false,
    description: "Latest Qwen generation with balanced all-around strength.",
  },
  {
    id: "qwen3-reasoning", provider: "openrouter", family: "qwen", displayName: "Qwen3 Reasoning",
    contextLength: 128000, maxOutputTokens: 16384,
    speedScore: 54, qualityScore: 93, reasoningScore: 96, codingScore: 88,
    mathScore: 95, writingScore: 84, multilingualScore: 90,
    visionSupport: false, toolCalling: true, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 91.0, healthScore: 93, isReal: false,
    description: "Deep-thinking Qwen for complex reasoning chains.",
  },
  {
    id: "qwen3.5", provider: "openrouter", family: "qwen", displayName: "Qwen3.5",
    contextLength: 256000, maxOutputTokens: 8192,
    speedScore: 74, qualityScore: 92, reasoningScore: 91, codingScore: 90,
    mathScore: 91, writingScore: 90, multilingualScore: 94,
    visionSupport: false, toolCalling: true, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 90.6, healthScore: 94, isReal: false,
    description: "Mid-generation refresh with extended 256K context.",
  },
  {
    id: "qwen3.6", provider: "openrouter", family: "qwen", displayName: "Qwen3.6",
    contextLength: 256000, maxOutputTokens: 8192,
    speedScore: 76, qualityScore: 93, reasoningScore: 92, codingScore: 91,
    mathScore: 92, writingScore: 91, multilingualScore: 94,
    visionSupport: true, toolCalling: true, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 91.5, healthScore: 93, isReal: false,
    description: "Multimodal Qwen with vision and refined reasoning.",
  },

  // ===================== Google Gemma =====================
  {
    id: "gemma-3", provider: "openrouter", family: "gemma", displayName: "Gemma 3",
    contextLength: 128000, maxOutputTokens: 8192,
    speedScore: 80, qualityScore: 86, reasoningScore: 82, codingScore: 80,
    mathScore: 78, writingScore: 86, multilingualScore: 88,
    visionSupport: true, toolCalling: false, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 83.2, healthScore: 97, isReal: false,
    description: "Google's open model with strong multilingual and vision support.",
  },
  {
    id: "gemma-4", provider: "openrouter", family: "gemma", displayName: "Gemma 4",
    contextLength: 256000, maxOutputTokens: 8192,
    speedScore: 82, qualityScore: 89, reasoningScore: 87, codingScore: 84,
    mathScore: 83, writingScore: 89, multilingualScore: 90,
    visionSupport: true, toolCalling: true, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 86.7, healthScore: 96, isReal: false,
    description: "Next-gen Gemma with tool calling and longer context.",
  },

  // ===================== Meta Llama =====================
  {
    id: "llama-3", provider: "openrouter", family: "llama", displayName: "Llama 3",
    contextLength: 8000, maxOutputTokens: 4096,
    speedScore: 88, qualityScore: 84, reasoningScore: 80, codingScore: 78,
    mathScore: 76, writingScore: 85, multilingualScore: 82,
    visionSupport: false, toolCalling: false, functionCalling: true, jsonMode: true,
    structuredOutput: false, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 80.1, healthScore: 95, isReal: false,
    description: "Foundational Llama 3; fast and reliable for general chat.",
  },
  {
    id: "llama-3.1", provider: "openrouter", family: "llama", displayName: "Llama 3.1",
    contextLength: 128000, maxOutputTokens: 8192,
    speedScore: 84, qualityScore: 88, reasoningScore: 86, codingScore: 84,
    mathScore: 82, writingScore: 88, multilingualScore: 85,
    visionSupport: false, toolCalling: true, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 85.9, healthScore: 96, isReal: false,
    description: "Llama 3.1 with 128K context and tool calling.",
  },
  {
    id: "llama-4-scout", provider: "openrouter", family: "llama", displayName: "Llama 4 Scout",
    contextLength: 10000000, maxOutputTokens: 8192,
    speedScore: 78, qualityScore: 90, reasoningScore: 88, codingScore: 86,
    mathScore: 85, writingScore: 88, multilingualScore: 86,
    visionSupport: true, toolCalling: true, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 87.4, healthScore: 93, isReal: false,
    description: "Llama 4 Scout with industry-leading 10M context.",
  },
  {
    id: "llama-4-maverick", provider: "openrouter", family: "llama", displayName: "Llama 4 Maverick",
    contextLength: 1000000, maxOutputTokens: 8192,
    speedScore: 70, qualityScore: 92, reasoningScore: 91, codingScore: 90,
    mathScore: 89, writingScore: 91, multilingualScore: 88,
    visionSupport: true, toolCalling: true, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 89.8, healthScore: 92, isReal: false,
    description: "Frontier Llama 4 balancing quality and 1M context.",
  },
  {
    id: "llama-4-behemoth", provider: "openrouter", family: "llama", displayName: "Llama 4 Behemoth",
    contextLength: 1000000, maxOutputTokens: 16384,
    speedScore: 48, qualityScore: 95, reasoningScore: 95, codingScore: 93,
    mathScore: 94, writingScore: 94, multilingualScore: 90,
    visionSupport: true, toolCalling: true, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 92.6, healthScore: 88, isReal: false,
    description: "Largest Llama 4; maximum quality at the cost of latency.",
  },

  // ===================== Mistral =====================
  {
    id: "mistral-7b", provider: "openrouter", family: "mistral", displayName: "Mistral 7B",
    contextLength: 32000, maxOutputTokens: 4096,
    speedScore: 92, qualityScore: 82, reasoningScore: 78, codingScore: 80,
    mathScore: 76, writingScore: 83, multilingualScore: 84,
    visionSupport: false, toolCalling: false, functionCalling: true, jsonMode: true,
    structuredOutput: false, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 79.4, healthScore: 97, isReal: false,
    description: "Fast, lightweight open model ideal for low-latency chat.",
  },
  {
    id: "mixtral", provider: "openrouter", family: "mistral", displayName: "Mixtral 8x7B",
    contextLength: 32000, maxOutputTokens: 8192,
    speedScore: 82, qualityScore: 87, reasoningScore: 85, codingScore: 86,
    mathScore: 83, writingScore: 86, multilingualScore: 87,
    visionSupport: false, toolCalling: true, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 85.1, healthScore: 95, isReal: false,
    description: "Sparse MoE model offering strong quality at good speed.",
  },
  {
    id: "leanstral", provider: "openrouter", family: "mistral", displayName: "Leanstral",
    contextLength: 64000, maxOutputTokens: 8192,
    speedScore: 80, qualityScore: 86, reasoningScore: 88, codingScore: 84,
    mathScore: 90, writingScore: 82, multilingualScore: 84,
    visionSupport: false, toolCalling: true, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 85.0, healthScore: 94, isReal: false,
    description: "Mistral fine-tuned for formal mathematical reasoning (Lean).",
  },

  // ===================== Microsoft Phi =====================
  {
    id: "phi-4", provider: "openrouter", family: "phi", displayName: "Phi-4",
    contextLength: 16000, maxOutputTokens: 4096,
    speedScore: 90, qualityScore: 87, reasoningScore: 88, codingScore: 85,
    mathScore: 90, writingScore: 84, multilingualScore: 80,
    visionSupport: false, toolCalling: true, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 85.5, healthScore: 96, isReal: false,
    description: "Compact Microsoft model with outsized math and reasoning.",
  },

  // ===================== IBM Granite =====================
  {
    id: "granite-3.3", provider: "openrouter", family: "granite", displayName: "IBM Granite 3.3",
    contextLength: 128000, maxOutputTokens: 8192,
    speedScore: 82, qualityScore: 84, reasoningScore: 82, codingScore: 83,
    mathScore: 80, writingScore: 82, multilingualScore: 86,
    visionSupport: false, toolCalling: true, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: true, streaming: true,
    freeOrPaid: "free", benchmarkScore: 82.8, healthScore: 96, isReal: false,
    description: "Enterprise-tuned model with strong embedding and tool support.",
  },

  // ===================== NVIDIA Nemotron =====================
  {
    id: "nemotron-70b", provider: "openrouter", family: "nemotron", displayName: "Nemotron 70B",
    contextLength: 128000, maxOutputTokens: 8192,
    speedScore: 72, qualityScore: 88, reasoningScore: 87, codingScore: 85,
    mathScore: 84, writingScore: 86, multilingualScore: 84,
    visionSupport: false, toolCalling: true, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 85.2, healthScore: 94, isReal: false,
    description: "NVIDIA-tuned Llama variant optimized for instruction following.",
  },
  {
    id: "nemotron-nano", provider: "openrouter", family: "nemotron", displayName: "Nemotron Nano",
    contextLength: 128000, maxOutputTokens: 4096,
    speedScore: 94, qualityScore: 80, reasoningScore: 78, codingScore: 76,
    mathScore: 77, writingScore: 80, multilingualScore: 78,
    visionSupport: false, toolCalling: true, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 78.3, healthScore: 97, isReal: false,
    description: "Compact Nemotron for edge and high-throughput inference.",
  },
  {
    id: "nemotron-super", provider: "openrouter", family: "nemotron", displayName: "Nemotron Super",
    contextLength: 256000, maxOutputTokens: 8192,
    speedScore: 74, qualityScore: 90, reasoningScore: 89, codingScore: 88,
    mathScore: 88, writingScore: 88, multilingualScore: 85,
    visionSupport: true, toolCalling: true, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 87.9, healthScore: 93, isReal: false,
    description: "High-accuracy Nemotron with vision and long context.",
  },

  // ===================== Tencent Hunyuan =====================
  {
    id: "hunyuan-hy3", provider: "openrouter", family: "hunyuan", displayName: "Tencent Hy3",
    contextLength: 256000, maxOutputTokens: 8192,
    speedScore: 76, qualityScore: 88, reasoningScore: 87, codingScore: 84,
    mathScore: 85, writingScore: 89, multilingualScore: 91,
    visionSupport: false, toolCalling: true, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 86.1, healthScore: 94, isReal: false,
    description: "Tencent's MoE model with strong Chinese-English coverage.",
  },

  // ===================== Liquid AI LFM =====================
  {
    id: "lfm-7b", provider: "openrouter", family: "lfm", displayName: "Liquid LFM 7B",
    contextLength: 32000, maxOutputTokens: 4096,
    speedScore: 93, qualityScore: 81, reasoningScore: 78, codingScore: 77,
    mathScore: 75, writingScore: 82, multilingualScore: 80,
    visionSupport: false, toolCalling: false, functionCalling: true, jsonMode: true,
    structuredOutput: false, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 78.9, healthScore: 96, isReal: false,
    description: "Hybrid liquid foundation model; extremely memory-efficient.",
  },
  {
    id: "lfm-40b", provider: "openrouter", family: "lfm", displayName: "Liquid LFM 40B MoE",
    contextLength: 32000, maxOutputTokens: 8192,
    speedScore: 80, qualityScore: 87, reasoningScore: 85, codingScore: 84,
    mathScore: 83, writingScore: 86, multilingualScore: 84,
    visionSupport: false, toolCalling: true, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 84.2, healthScore: 94, isReal: false,
    description: "MoE liquid model scaling quality while keeping memory low.",
  },
  {
    id: "lfm-vision", provider: "openrouter", family: "lfm", displayName: "Liquid LFM Vision",
    contextLength: 32000, maxOutputTokens: 4096,
    speedScore: 86, qualityScore: 84, reasoningScore: 80, codingScore: 78,
    mathScore: 76, writingScore: 83, multilingualScore: 80,
    visionSupport: true, toolCalling: false, functionCalling: true, jsonMode: true,
    structuredOutput: false, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 80.5, healthScore: 95, isReal: false,
    description: "Multimodal liquid model for image understanding.",
  },

  // ===================== Sarvam =====================
  {
    id: "sarvam-2b", provider: "openrouter", family: "sarvam", displayName: "Sarvam 2B",
    contextLength: 8000, maxOutputTokens: 2048,
    speedScore: 95, qualityScore: 76, reasoningScore: 72, codingScore: 70,
    mathScore: 71, writingScore: 78, multilingualScore: 96,
    visionSupport: false, toolCalling: false, functionCalling: false, jsonMode: false,
    structuredOutput: false, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 74.0, healthScore: 97, isReal: false,
    description: "Indic-language specialist covering 10+ Indian languages.",
  },
  {
    id: "sarvam-m-f", provider: "openrouter", family: "sarvam", displayName: "Sarvam M-F",
    contextLength: 32000, maxOutputTokens: 4096,
    speedScore: 88, qualityScore: 82, reasoningScore: 80, codingScore: 78,
    mathScore: 79, writingScore: 84, multilingualScore: 95,
    visionSupport: true, toolCalling: true, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 82.1, healthScore: 95, isReal: false,
    description: "Multimodal Sarvam for Indic + English multimodal tasks.",
  },

  // ===================== Prism ML =====================
  {
    id: "bonsai-7b", provider: "openrouter", family: "bonsai", displayName: "Prism Bonsai 7B",
    contextLength: 16000, maxOutputTokens: 4096,
    speedScore: 91, qualityScore: 80, reasoningScore: 79, codingScore: 82,
    mathScore: 78, writingScore: 81, multilingualScore: 80,
    visionSupport: false, toolCalling: true, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 79.6, healthScore: 96, isReal: false,
    description: "Pruned sparse model with bonsai efficiency curves.",
  },
  {
    id: "ternary-bonsai", provider: "openrouter", family: "bonsai", displayName: "Ternary Bonsai",
    contextLength: 16000, maxOutputTokens: 4096,
    speedScore: 96, qualityScore: 77, reasoningScore: 75, codingScore: 76,
    mathScore: 74, writingScore: 78, multilingualScore: 78,
    visionSupport: false, toolCalling: false, functionCalling: true, jsonMode: true,
    structuredOutput: false, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 76.4, healthScore: 97, isReal: false,
    description: "Ternary-weight bonsai; ultra-fast, ultra-cheap inference.",
  },

  // ===================== OpenAI GPT-OSS =====================
  {
    id: "gpt-oss-120b", provider: "openrouter", family: "gpt-oss", displayName: "GPT-OSS 120B",
    contextLength: 128000, maxOutputTokens: 16384,
    speedScore: 68, qualityScore: 91, reasoningScore: 92, codingScore: 90,
    mathScore: 91, writingScore: 92, multilingualScore: 90,
    visionSupport: false, toolCalling: true, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 89.7, healthScore: 93, isReal: false,
    description: "Open-weight GPT model with strong reasoning and writing.",
  },
  {
    id: "gpt-oss-20b", provider: "openrouter", family: "gpt-oss", displayName: "GPT-OSS 20B",
    contextLength: 128000, maxOutputTokens: 8192,
    speedScore: 86, qualityScore: 85, reasoningScore: 84, codingScore: 83,
    mathScore: 83, writingScore: 86, multilingualScore: 84,
    visionSupport: false, toolCalling: true, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 83.4, healthScore: 96, isReal: false,
    description: "Smaller GPT-OSS for fast, capable general inference.",
  },

  // ===================== H Company Holo =====================
  {
    id: "holo-1-3b", provider: "openrouter", family: "holo", displayName: "Holo 1 3B",
    contextLength: 16000, maxOutputTokens: 4096,
    speedScore: 94, qualityScore: 76, reasoningScore: 74, codingScore: 73,
    mathScore: 72, writingScore: 79, multilingualScore: 78,
    visionSupport: false, toolCalling: false, functionCalling: true, jsonMode: true,
    structuredOutput: false, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 75.1, healthScore: 96, isReal: false,
    description: "Action-agent model optimized for tool use sequences.",
  },
  {
    id: "holo-1-7b", provider: "openrouter", family: "holo", displayName: "Holo 1 7B",
    contextLength: 32000, maxOutputTokens: 4096,
    speedScore: 89, qualityScore: 81, reasoningScore: 80, codingScore: 80,
    mathScore: 79, writingScore: 82, multilingualScore: 80,
    visionSupport: false, toolCalling: true, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 80.0, healthScore: 95, isReal: false,
    description: "Mid-size Holo agent model with strong action planning.",
  },
  {
    id: "holo-1-32b", provider: "openrouter", family: "holo", displayName: "Holo 1 32B",
    contextLength: 64000, maxOutputTokens: 8192,
    speedScore: 72, qualityScore: 88, reasoningScore: 89, codingScore: 87,
    mathScore: 86, writingScore: 86, multilingualScore: 84,
    visionSupport: false, toolCalling: true, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 86.3, healthScore: 93, isReal: false,
    description: "Large Holo agent model for complex multi-step agents.",
  },

  // ===================== LongCat =====================
  {
    id: "longcat-2.0", provider: "openrouter", family: "longcat", displayName: "LongCat 2.0",
    contextLength: 128000, maxOutputTokens: 8192,
    speedScore: 84, qualityScore: 87, reasoningScore: 85, codingScore: 84,
    mathScore: 83, writingScore: 87, multilingualScore: 86,
    visionSupport: false, toolCalling: true, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 84.6, healthScore: 95, isReal: false,
    description: "Long-context model tuned for stable retrieval at 128K.",
  },
  {
    id: "longcat-flash", provider: "openrouter", family: "longcat", displayName: "LongCat Flash",
    contextLength: 128000, maxOutputTokens: 8192,
    speedScore: 92, qualityScore: 83, reasoningScore: 80, codingScore: 80,
    mathScore: 79, writingScore: 83, multilingualScore: 82,
    visionSupport: false, toolCalling: true, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 81.2, healthScore: 97, isReal: false,
    description: "Fast LongCat variant for high-throughput long-context.",
  },

  // ===================== MiMo =====================
  {
    id: "mimo-7b", provider: "openrouter", family: "mimo", displayName: "MiMo 7B",
    contextLength: 32000, maxOutputTokens: 4096,
    speedScore: 93, qualityScore: 83, reasoningScore: 85, codingScore: 86,
    mathScore: 84, writingScore: 82, multilingualScore: 80,
    visionSupport: false, toolCalling: true, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 82.8, healthScore: 96, isReal: false,
    description: "Reasoning-tuned compact model from Xiaomi MiMo line.",
  },
  {
    id: "mimo-flash", provider: "openrouter", family: "mimo", displayName: "MiMo Flash",
    contextLength: 32000, maxOutputTokens: 4096,
    speedScore: 97, qualityScore: 80, reasoningScore: 81, codingScore: 82,
    mathScore: 80, writingScore: 80, multilingualScore: 79,
    visionSupport: false, toolCalling: true, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 80.0, healthScore: 98, isReal: false,
    description: "Fastest MiMo variant; sub-second first-token latency.",
  },

  // ===================== Zyphra ZAYA =====================
  {
    id: "zaya-7b", provider: "openrouter", family: "zaya", displayName: "Zyphra ZAYA 7B",
    contextLength: 32000, maxOutputTokens: 4096,
    speedScore: 90, qualityScore: 82, reasoningScore: 80, codingScore: 79,
    mathScore: 78, writingScore: 85, multilingualScore: 84,
    visionSupport: false, toolCalling: true, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 80.9, healthScore: 95, isReal: false,
    description: "State-space hybrid; excels in creative writing and audio.",
  },
  {
    id: "zaya-22b", provider: "openrouter", family: "zaya", displayName: "Zyphra ZAYA 22B",
    contextLength: 64000, maxOutputTokens: 8192,
    speedScore: 78, qualityScore: 87, reasoningScore: 86, codingScore: 84,
    mathScore: 83, writingScore: 90, multilingualScore: 86,
    visionSupport: false, toolCalling: true, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 85.0, healthScore: 93, isReal: false,
    description: "Larger ZAYA with refined multilingual and writing quality.",
  },

  // ===================== Ornith =====================
  {
    id: "ornith-14b", provider: "openrouter", family: "ornith", displayName: "Ornith 14B",
    contextLength: 64000, maxOutputTokens: 8192,
    speedScore: 82, qualityScore: 85, reasoningScore: 84, codingScore: 83,
    mathScore: 82, writingScore: 85, multilingualScore: 83,
    visionSupport: false, toolCalling: true, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 83.1, healthScore: 94, isReal: false,
    description: "Open bird-class model with steady all-around scores.",
  },
  {
    id: "ornith-32b", provider: "openrouter", family: "ornith", displayName: "Ornith 32B",
    contextLength: 128000, maxOutputTokens: 8192,
    speedScore: 74, qualityScore: 88, reasoningScore: 88, codingScore: 86,
    mathScore: 86, writingScore: 88, multilingualScore: 85,
    visionSupport: true, toolCalling: true, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 86.2, healthScore: 93, isReal: false,
    description: "Larger Ornith with vision and long context.",
  },

  // ===================== Cloudflare AI (workers models) =====================
  {
    id: "cf-llama-3.1-8b", provider: "cloudflare", family: "llama", displayName: "CF Llama 3.1 8B",
    contextLength: 128000, maxOutputTokens: 4096,
    speedScore: 95, qualityScore: 84, reasoningScore: 82, codingScore: 81,
    mathScore: 80, writingScore: 85, multilingualScore: 83,
    visionSupport: false, toolCalling: true, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 83.0, healthScore: 99, isReal: false,
    description: "Edge-deployed Llama on Cloudflare Workers AI; very low latency.",
  },
  {
    id: "cf-mistral-7b", provider: "cloudflare", family: "mistral", displayName: "CF Mistral 7B",
    contextLength: 32000, maxOutputTokens: 4096,
    speedScore: 96, qualityScore: 81, reasoningScore: 77, codingScore: 79,
    mathScore: 75, writingScore: 82, multilingualScore: 83,
    visionSupport: false, toolCalling: false, functionCalling: true, jsonMode: true,
    structuredOutput: false, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 78.8, healthScore: 99, isReal: false,
    description: "Edge Mistral on Cloudflare; ideal for global low-latency chat.",
  },
  {
    id: "cf-qwen-1.5-14b", provider: "cloudflare", family: "qwen", displayName: "CF Qwen 1.5 14B",
    contextLength: 32000, maxOutputTokens: 4096,
    speedScore: 91, qualityScore: 83, reasoningScore: 81, codingScore: 82,
    mathScore: 80, writingScore: 83, multilingualScore: 88,
    visionSupport: false, toolCalling: true, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 81.5, healthScore: 98, isReal: false,
    description: "Edge Qwen for multilingual edge inference.",
  },
  {
    id: "cf-bge-embeddings", provider: "cloudflare", family: "bge", displayName: "CF BGE Embeddings",
    contextLength: 8000, maxOutputTokens: 1024,
    speedScore: 98, qualityScore: 80, reasoningScore: 0, codingScore: 0,
    mathScore: 0, writingScore: 0, multilingualScore: 90,
    visionSupport: false, toolCalling: false, functionCalling: false, jsonMode: false,
    structuredOutput: false, embeddingSupport: true, streaming: false,
    freeOrPaid: "free", benchmarkScore: 78.0, healthScore: 99, isReal: false,
    description: "Edge embedding model for semantic search and RAG.",
  },

  // ===================== HuggingFace / community =====================
  {
    id: "hf-zephyr-7b", provider: "huggingface", family: "mistral", displayName: "Zephyr 7B Beta",
    contextLength: 32000, maxOutputTokens: 4096,
    speedScore: 90, qualityScore: 82, reasoningScore: 80, codingScore: 79,
    mathScore: 78, writingScore: 84, multilingualScore: 82,
    visionSupport: false, toolCalling: false, functionCalling: true, jsonMode: true,
    structuredOutput: false, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 79.8, healthScore: 94, isReal: false,
    description: "DPO-tuned Mistral; strong conversational quality.",
  },
  {
    id: "hf-starling-7b", provider: "huggingface", family: "starling", displayName: "Starling 7B",
    contextLength: 32000, maxOutputTokens: 4096,
    speedScore: 89, qualityScore: 83, reasoningScore: 81, codingScore: 80,
    mathScore: 79, writingScore: 85, multilingualScore: 81,
    visionSupport: false, toolCalling: false, functionCalling: true, jsonMode: true,
    structuredOutput: false, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 80.6, healthScore: 93, isReal: false,
    description: "RLHF-tuned model optimized for helpfulness.",
  },
  {
    id: "hf-openhermes-2.5", provider: "huggingface", family: "hermes", displayName: "OpenHermes 2.5",
    contextLength: 32000, maxOutputTokens: 4096,
    speedScore: 88, qualityScore: 82, reasoningScore: 81, codingScore: 82,
    mathScore: 80, writingScore: 83, multilingualScore: 82,
    visionSupport: false, toolCalling: true, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 81.0, healthScore: 93, isReal: false,
    description: "Synthetic-data fine-tune with strong JSON mode support.",
  },
  {
    id: "hf-dolphin-mistral", provider: "huggingface", family: "dolphin", displayName: "Dolphin Mistral",
    contextLength: 32000, maxOutputTokens: 4096,
    speedScore: 87, qualityScore: 81, reasoningScore: 80, codingScore: 81,
    mathScore: 78, writingScore: 83, multilingualScore: 80,
    visionSupport: false, toolCalling: true, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 80.2, healthScore: 92, isReal: false,
    description: "Uncensored fine-tune for flexible instruction following.",
  },
  {
    id: "hf-bge-m3", provider: "huggingface", family: "bge", displayName: "BGE M3 Embeddings",
    contextLength: 8000, maxOutputTokens: 1024,
    speedScore: 95, qualityScore: 84, reasoningScore: 0, codingScore: 0,
    mathScore: 0, writingScore: 0, multilingualScore: 95,
    visionSupport: false, toolCalling: false, functionCalling: false, jsonMode: false,
    structuredOutput: false, embeddingSupport: true, streaming: false,
    freeOrPaid: "free", benchmarkScore: 82.0, healthScore: 96, isReal: false,
    description: "Multilingual embedding model for semantic caching & RAG.",
  },

  // ===================== GitHub Models =====================
  {
    id: "gh-phi-4", provider: "github", family: "phi", displayName: "GitHub Phi-4",
    contextLength: 16000, maxOutputTokens: 4096,
    speedScore: 90, qualityScore: 86, reasoningScore: 88, codingScore: 85,
    mathScore: 90, writingScore: 84, multilingualScore: 80,
    visionSupport: false, toolCalling: true, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 85.0, healthScore: 95, isReal: false,
    description: "Phi-4 served via GitHub Models free tier.",
  },
  {
    id: "gh-gpt-4o-mini", provider: "github", family: "gpt-oss", displayName: "GitHub GPT-4o mini",
    contextLength: 128000, maxOutputTokens: 8192,
    speedScore: 88, qualityScore: 88, reasoningScore: 86, codingScore: 85,
    mathScore: 85, writingScore: 88, multilingualScore: 88,
    visionSupport: true, toolCalling: true, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 86.5, healthScore: 96, isReal: false,
    description: "GPT-4o mini via GitHub Models; balanced multimodal.",
  },
  {
    id: "gh-llama-3.1-8b", provider: "github", family: "llama", displayName: "GitHub Llama 3.1 8B",
    contextLength: 128000, maxOutputTokens: 4096,
    speedScore: 92, qualityScore: 85, reasoningScore: 83, codingScore: 82,
    mathScore: 80, writingScore: 86, multilingualScore: 83,
    visionSupport: false, toolCalling: true, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 83.5, healthScore: 96, isReal: false,
    description: "Llama 3.1 8B via GitHub Models free tier.",
  },
  {
    id: "gh-mistral-large", provider: "github", family: "mistral", displayName: "GitHub Mistral Large",
    contextLength: 32000, maxOutputTokens: 8192,
    speedScore: 78, qualityScore: 89, reasoningScore: 88, codingScore: 87,
    mathScore: 85, writingScore: 89, multilingualScore: 88,
    visionSupport: false, toolCalling: true, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 87.0, healthScore: 94, isReal: false,
    description: "Mistral Large via GitHub Models; strong reasoning.",
  },

  // ===================== Ollama (local) =====================
  {
    id: "ollama-llama3.2", provider: "ollama", family: "llama", displayName: "Ollama Llama 3.2",
    contextLength: 128000, maxOutputTokens: 4096,
    speedScore: 85, qualityScore: 84, reasoningScore: 82, codingScore: 81,
    mathScore: 79, writingScore: 85, multilingualScore: 82,
    visionSupport: false, toolCalling: true, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 82.0, healthScore: 90, isReal: false,
    description: "Self-hosted Llama 3.2 via Ollama runtime.",
  },
  {
    id: "ollama-qwen2.5", provider: "ollama", family: "qwen", displayName: "Ollama Qwen2.5",
    contextLength: 128000, maxOutputTokens: 8192,
    speedScore: 83, qualityScore: 88, reasoningScore: 86, codingScore: 88,
    mathScore: 86, writingScore: 87, multilingualScore: 92,
    visionSupport: false, toolCalling: true, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 86.0, healthScore: 90, isReal: false,
    description: "Self-hosted Qwen2.5 via Ollama; private inference.",
  },
  {
    id: "ollama-deepseek-r1", provider: "ollama", family: "deepseek", displayName: "Ollama DeepSeek R1",
    contextLength: 64000, maxOutputTokens: 16384,
    speedScore: 70, qualityScore: 90, reasoningScore: 93, codingScore: 88,
    mathScore: 94, writingScore: 82, multilingualScore: 82,
    visionSupport: false, toolCalling: true, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 88.0, healthScore: 88, isReal: false,
    description: "Self-hosted DeepSeek R1 reasoning via Ollama.",
  },
  {
    id: "ollama-phi4", provider: "ollama", family: "phi", displayName: "Ollama Phi-4",
    contextLength: 16000, maxOutputTokens: 4096,
    speedScore: 91, qualityScore: 85, reasoningScore: 87, codingScore: 84,
    mathScore: 89, writingScore: 83, multilingualScore: 80,
    visionSupport: false, toolCalling: true, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 84.0, healthScore: 89, isReal: false,
    description: "Self-hosted Phi-4 via Ollama.",
  },
  {
    id: "ollama-nomic-embed", provider: "ollama", family: "nomic", displayName: "Ollama Nomic Embed",
    contextLength: 8000, maxOutputTokens: 1024,
    speedScore: 97, qualityScore: 82, reasoningScore: 0, codingScore: 0,
    mathScore: 0, writingScore: 0, multilingualScore: 88,
    visionSupport: false, toolCalling: false, functionCalling: false, jsonMode: false,
    structuredOutput: false, embeddingSupport: true, streaming: false,
    freeOrPaid: "free", benchmarkScore: 79.0, healthScore: 90, isReal: false,
    description: "Self-hosted embedding model for private RAG.",
  },

  // ===================== LM Studio (local GGUF) =====================
  {
    id: "lms-qwen2.5-coder", provider: "lmstudio", family: "qwen", displayName: "LM Studio Qwen2.5 Coder",
    contextLength: 64000, maxOutputTokens: 8192,
    speedScore: 80, qualityScore: 89, reasoningScore: 84, codingScore: 94,
    mathScore: 80, writingScore: 76, multilingualScore: 86,
    visionSupport: false, toolCalling: true, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 86.5, healthScore: 88, isReal: false,
    description: "Local GGUF Qwen coder via LM Studio.",
  },
  {
    id: "lms-llama3.1-8b", provider: "lmstudio", family: "llama", displayName: "LM Studio Llama 3.1 8B",
    contextLength: 128000, maxOutputTokens: 4096,
    speedScore: 86, qualityScore: 84, reasoningScore: 82, codingScore: 81,
    mathScore: 79, writingScore: 85, multilingualScore: 82,
    visionSupport: false, toolCalling: true, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 82.5, healthScore: 88, isReal: false,
    description: "Local GGUF Llama 3.1 via LM Studio.",
  },

  // ===================== Local GGUF (llama.cpp) =====================
  {
    id: "gguf-mistral-nemo", provider: "local-gguf", family: "mistral", displayName: "GGUF Mistral Nemo",
    contextLength: 128000, maxOutputTokens: 8192,
    speedScore: 82, qualityScore: 86, reasoningScore: 84, codingScore: 83,
    mathScore: 81, writingScore: 86, multilingualScore: 89,
    visionSupport: false, toolCalling: true, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 84.0, healthScore: 85, isReal: false,
    description: "Quantized Mistral Nemo via llama.cpp.",
  },
  {
    id: "gguf-hermes-3", provider: "local-gguf", family: "hermes", displayName: "GGUF Hermes 3",
    contextLength: 64000, maxOutputTokens: 8192,
    speedScore: 78, qualityScore: 87, reasoningScore: 87, codingScore: 85,
    mathScore: 84, writingScore: 88, multilingualScore: 84,
    visionSupport: false, toolCalling: true, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 85.5, healthScore: 84, isReal: false,
    description: "Quantized Hermes 3 via llama.cpp; strong generalism.",
  },

  // ===================== OpenAI-Compatible APIs (community) =====================
  {
    id: "oai-llama-3.3-70b", provider: "openai-compatible", family: "llama", displayName: "Llama 3.3 70B",
    contextLength: 128000, maxOutputTokens: 8192,
    speedScore: 72, qualityScore: 91, reasoningScore: 90, codingScore: 89,
    mathScore: 88, writingScore: 91, multilingualScore: 87,
    visionSupport: false, toolCalling: true, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 88.5, healthScore: 92, isReal: false,
    description: "Llama 3.3 70B via OpenAI-compatible gateway.",
  },
  {
    id: "oai-gemma-3-27b", provider: "openai-compatible", family: "gemma", displayName: "Gemma 3 27B",
    contextLength: 128000, maxOutputTokens: 8192,
    speedScore: 80, qualityScore: 87, reasoningScore: 85, codingScore: 83,
    mathScore: 82, writingScore: 88, multilingualScore: 89,
    visionSupport: true, toolCalling: true, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 85.4, healthScore: 93, isReal: false,
    description: "Gemma 3 27B via OpenAI-compatible gateway.",
  },
  {
    id: "oai-mistral-small", provider: "openai-compatible", family: "mistral", displayName: "Mistral Small",
    contextLength: 32000, maxOutputTokens: 8192,
    speedScore: 90, qualityScore: 85, reasoningScore: 83, codingScore: 84,
    mathScore: 82, writingScore: 86, multilingualScore: 85,
    visionSupport: false, toolCalling: true, functionCalling: true, jsonMode: true,
    structuredOutput: true, embeddingSupport: false, streaming: true,
    freeOrPaid: "free", benchmarkScore: 84.0, healthScore: 94, isReal: false,
    description: "Mistral Small via OpenAI-compatible gateway; fast & cheap.",
  },
];

export const PROVIDERS = [
  { id: "zai", name: "Z.AI", color: "#10b981", description: "Native GLM provider (live)" },
  { id: "openrouter", name: "OpenRouter", color: "#6366f1", description: "Aggregator of 100+ models" },
  { id: "huggingface", name: "HuggingFace", color: "#f59e0b", description: "Community open models" },
  { id: "cloudflare", name: "Cloudflare AI", color: "#ef4444", description: "Edge inference" },
  { id: "github", name: "GitHub Models", color: "#8b5cf6", description: "GitHub free tier" },
  { id: "ollama", name: "Ollama", color: "#14b8a6", description: "Local runtime" },
  { id: "lmstudio", name: "LM Studio", color: "#ec4899", description: "Local GGUF loader" },
  { id: "local-gguf", name: "Local GGUF", color: "#a3a3a3", description: "llama.cpp runtime" },
  { id: "openai-compatible", name: "OpenAI-Compatible", color: "#0ea5e9", description: "Community gateways" },
];

export const INTENT_TYPES = [
  { id: "general_chat", label: "General Chat", icon: "MessageCircle", color: "#10b981" },
  { id: "coding", label: "Coding", icon: "Code2", color: "#6366f1" },
  { id: "debugging", label: "Debugging", icon: "Bug", color: "#ef4444" },
  { id: "code_review", label: "Code Review", icon: "FileSearch", color: "#8b5cf6" },
  { id: "architecture", label: "Architecture", icon: "Building2", color: "#0ea5e9" },
  { id: "reasoning", label: "Reasoning", icon: "Brain", color: "#f59e0b" },
  { id: "mathematics", label: "Mathematics", icon: "Sigma", color: "#14b8a6" },
  { id: "creative_writing", label: "Creative Writing", icon: "PenLine", color: "#ec4899" },
  { id: "translation", label: "Translation", icon: "Languages", color: "#a855f7" },
  { id: "research", label: "Research", icon: "Search", color: "#3b82f6" },
  { id: "summarization", label: "Summarization", icon: "FileText", color: "#0891b2" },
  { id: "ocr", label: "OCR", icon: "ScanText", color: "#dc2626" },
  { id: "vision", label: "Vision", icon: "Eye", color: "#7c3aed" },
  { id: "long_context", label: "Long Context", icon: "ScrollText", color: "#0d9488" },
  { id: "tool_calling", label: "Tool Calling", icon: "Wrench", color: "#ca8a04" },
  { id: "function_calling", label: "Function Calling", icon: "Webhook", color: "#9333ea" },
  { id: "json_generation", label: "JSON Generation", icon: "Braces", color: "#2563eb" },
  { id: "sql", label: "SQL", icon: "Database", color: "#059669" },
  { id: "data_analysis", label: "Data Analysis", icon: "BarChart3", color: "#d97706" },
  { id: "agent_tasks", label: "Agent Tasks", icon: "Bot", color: "#be185d" },
  { id: "rag", label: "RAG", icon: "Library", color: "#4f46e5" },
  { id: "planning", label: "Planning", icon: "ListChecks", color: "#16a34a" },
  { id: "education", label: "Education", icon: "GraduationCap", color: "#9333ea" },
  { id: "legal", label: "Legal", icon: "Scale", color: "#475569" },
  { id: "finance", label: "Finance", icon: "TrendingUp", color: "#15803d" },
  { id: "medical", label: "Medical", icon: "Stethoscope", color: "#dc2626" },
  { id: "brainstorming", label: "Brainstorming", icon: "Lightbulb", color: "#eab308" },
];

export function getProvider(id: string) {
  return PROVIDERS.find((p) => p.id === id);
}

export function getModel(id: string): ModelCapability | undefined {
  return MODEL_REGISTRY.find((m) => m.id === id);
}
